"""empty message

Revision ID: 09dafeeccf95
Revises: 269618af470c
Create Date: 2016-11-09 21:56:32.182155

"""

# revision identifiers, used by Alembic.
revision = '09dafeeccf95'
down_revision = '269618af470c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('address', sa.String(length=240), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'address')
    ### end Alembic commands ###
