"""empty message

Revision ID: 19da8b4544a9
Revises: d2bb18e338b9
Create Date: 2016-10-24 07:05:36.912536

"""

# revision identifiers, used by Alembic.
revision = '19da8b4544a9'
down_revision = 'd2bb18e338b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('price', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'price')
    ### end Alembic commands ###
