"""empty message

Revision ID: 1b1f06049338
Revises: 80339a01e273
Create Date: 2016-10-27 17:45:17.663956

"""

# revision identifiers, used by Alembic.
revision = '1b1f06049338'
down_revision = '80339a01e273'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('region', sa.String(length=24), nullable=True))
    op.alter_column('posts', 'price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('posts', 'region')
    ### end Alembic commands ###
