"""empty message

Revision ID: 269618af470c
Revises: fec0d4e63c62
Create Date: 2016-11-03 19:11:04.145672

"""

# revision identifiers, used by Alembic.
revision = '269618af470c'
down_revision = 'fec0d4e63c62'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('posts', sa.Column('kakaotalk', sa.String(length=30), nullable=True))
    op.add_column('posts', sa.Column('phone', sa.String(length=12), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'phone')
    op.drop_column('posts', 'kakaotalk')
    op.drop_column('posts', 'email')
    ### end Alembic commands ###
