"""empty message

Revision ID: 56d9a663c29d
Revises: ce9550d2beec
Create Date: 2016-11-14 07:11:06.077393

"""

# revision identifiers, used by Alembic.
revision = '56d9a663c29d'
down_revision = 'ce9550d2beec'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'body',
               existing_type=mysql.TEXT(collation='utf8_unicode_ci'),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'body',
               existing_type=mysql.TEXT(collation='utf8_unicode_ci'),
               nullable=True)
    ### end Alembic commands ###
