"""empty message

Revision ID: 59c0d14826d1
Revises: 09dafeeccf95
Create Date: 2016-11-09 22:00:51.515307

"""

# revision identifiers, used by Alembic.
revision = '59c0d14826d1'
down_revision = '09dafeeccf95'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('city', sa.String(length=24), nullable=True))
    op.drop_column('posts', 'region')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('region', mysql.VARCHAR(collation='utf8_unicode_ci', length=24), nullable=True))
    op.drop_column('posts', 'city')
    ### end Alembic commands ###
