"""empty message

Revision ID: 80339a01e273
Revises: 19da8b4544a9
Create Date: 2016-10-26 09:04:30.238880

"""

# revision identifiers, used by Alembic.
revision = '80339a01e273'
down_revision = '19da8b4544a9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'parking')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('parking', mysql.INTEGER(display_width=2), autoincrement=False, nullable=True))
    ### end Alembic commands ###
