"""empty message

Revision ID: d160551d79ac
Revises: 9c36db55ec53
Create Date: 2016-10-20 05:34:10.269147

"""

# revision identifiers, used by Alembic.
revision = 'd160551d79ac'
down_revision = '9c36db55ec53'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', sa.String(length=120), nullable=False))
    op.alter_column('users', 'verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(collation='utf8_unicode_ci', length=120), nullable=False))
    op.alter_column('users', 'verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('users', '_password')
    ### end Alembic commands ###
