"""empty message

Revision ID: d2bb18e338b9
Revises: 913e02ad49f5
Create Date: 2016-10-24 06:31:19.867787

"""

# revision identifiers, used by Alembic.
revision = 'd2bb18e338b9'
down_revision = '913e02ad49f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('viewed', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'viewed')
    ### end Alembic commands ###
