"""empty message

Revision ID: f437d4a6a635
Revises: d160551d79ac
Create Date: 2016-10-20 07:49:22.593434

"""

# revision identifiers, used by Alembic.
revision = 'f437d4a6a635'
down_revision = 'd160551d79ac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=120), nullable=False))
    op.drop_column('users', '_password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', mysql.VARCHAR(collation='utf8_unicode_ci', length=120), nullable=False))
    op.drop_column('users', 'password')
    ### end Alembic commands ###
