"""empty message

Revision ID: fec0d4e63c62
Revises: 1b1f06049338
Create Date: 2016-10-27 21:55:55.754974

"""

# revision identifiers, used by Alembic.
revision = 'fec0d4e63c62'
down_revision = '1b1f06049338'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('parking', sa.String(length=6), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'parking')
    ### end Alembic commands ###
